plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace "com.apiproxy.local"
    compileSdk 35

    defaultConfig {
        applicationId "com.apiproxy.local"
        minSdk 26
        targetSdk 34
        versionCode 6
        versionName "1.1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file("Kars.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias "kars"
            keyPassword System.getenv("KEYSTORE_PASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.recyclerview
    implementation libs.gson
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
}
